### BankTransaction Creation ###

POST localhost:8080/banktransactions
Accept: application/json
Content-Type: application/json

{
  "bankTransactionId": "532588e7-2c23-4c09-afb6-d05cecc64708",
  "fromAccount": "NL50ABNA0705262425",
  "fromAccountHolder": "Jan Jansen",
  "toAccount": "NL50ABNA01245939",
  "toAccountHolder": "Pietje Puk",
  "currency": "EUR",
  "transactionDateTime" : "2020-08-01T11:43:06.908Z"
}
###

### BankTransaction Creation ###

POST localhost:8080/banktransactions/random
Accept: application/json
Content-Type: application/json

###

POST localhost:8080/banktransactions/532588e7-2c23-4c09-afb6-d05cecc64708/PARSED
Accept: application/json
Content-Type: application/json

###

POST localhost:8080/banktransactions/532588e7-2c23-4c09-afb6-d05cecc64708/FAILED
Accept: application/json
Content-Type: application/json

###
